# Generated by Django 2.1.5 on 2019-03-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='CursoId',
        ),
        migrations.AddField(
            model_name='cursos',
            name='CategoriaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Categorias'),
        ),
    ]
