# Generated by Django 2.1.5 on 2019-05-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190325_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CursoId', models.IntegerField(default=0)),
                ('EstudianteID', models.IntegerField(default=0)),
                ('Fecha', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='categorias',
            name='Descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Descripcion',
            field=models.TextField(),
        ),
    ]
